### ISSUE TITLE
Cannot connect to host iss.moex.com:443 ssl:default 

### ISSUE THREAD

**Issue by ArjaraGit** [WLM1ke/poptimizer#101]
Добрый вечер 
Подскажите пожалуйста с чем может быть связана ошибка? 
Появилась пару дней назад, с тех пор не может выкачать котировки за предыдущий день (падает при выгрузке каждый день)

[full_stacktrace.txt](https://github.com/WLM1ke/poptimizer/files/8006657/full_stacktrace.txt)

Traceback (most recent call last):
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/site-packages/aiohttp/connector.py", line 985, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/asyncio/base_events.py", line 1103, in _create_connection_transport
    transport = self._make_ssl_transport(
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/asyncio/selector_events.py", line 78, in _make_ssl_transport
    _SelectorSocketTransport(self, rawsock, ssl_protocol,
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/asyncio/selector_events.py", line 774, in __init__
    base_events._set_nodelay(self._sock)
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/asyncio/base_events.py", line 199, in _set_nodelay
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
OSError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/startEvolution.py", line 9, in <module>
    ev.evolve()
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/evolve/evolve.py", line 56, in evolve
    step, current = self._step_setup(step, current)
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/evolve/evolve.py", line 90, in _step_setup
    dates = listing.all_history_date(self._tickers, start=self._end)
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/views/listing.py", line 26, in all_history_date
    bus.handle_event(event)
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/shared/app.py", line 74, in handle_event
    loop.run_until_complete(self._handle_event(event))
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/shared/app.py", line 89, in _handle_event
    pending |= self._create_tasks(task.result())
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/shared/app.py", line 100, in _handle_one_command
    return await self._event_handler.handle_event(event, repo)
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/domain/handlers.py", line 92, in ticker_traded
    return list(itertools.chain.from_iterable(await asyncio.gather(*aws)))
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/domain/handlers.py", line 29, in _load_by_id_and_handle_event
    return await table.handle_event(event)
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/domain/tables/base.py", line 71, in handle_event
    df_new = await self._prepare_df(event)
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/domain/tables/quotes.py", line 39, in _prepare_df
    df_new = await self._load_df(event)
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/domain/tables/quotes.py", line 70, in _load_df
    await asyncio.gather(*aws),
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/adapters/gateways/moex.py", line 141, in __call__
    json = await aiomoex.get_market_candles(
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/site-packages/aiomoex/candles.py", line 116, in get_market_candles
    return await request_helpers.get_long_data(session, url, table, query)
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/site-packages/aiomoex/request_helpers.py", line 137, in get_long_data
    table_dict = await iss.get_all()
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/site-packages/aiomoex/client.py", line 112, in get_all
    async for block in self:
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/site-packages/aiomoex/client.py", line 131, in _iterator_maker
    respond = await self.get(start)
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/site-packages/aiomoex/client.py", line 94, in get
    async with self._session.get(url, params=query) as respond:
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/site-packages/aiohttp/client.py", line 1140, in __aenter__
    self._resp = await self._coro
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/site-packages/aiohttp/connector.py", line 543, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/site-packages/aiohttp/connector.py", line 906, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/site-packages/aiohttp/connector.py", line 1205, in _create_direct_connection
    raise last_exc
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/site-packages/aiohttp/connector.py", line 1174, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/opt/miniconda3/envs/torch39/lib/python3.9/site-packages/aiohttp/connector.py", line 991, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host iss.moex.com:443 ssl:default [Invalid argument]

**Comment by WLM1ke** [comment]
Какая-то проблема с ssl сертификатами, возможно вы давно не обновляли библиотеку certifi

**Comment by ArjaraGit** [comment]
обновил библиотеки в виртуальном окружении, удалил дату последней выгрузки котировок в misk/trading_dates
перезапустил эволюцию 
получаю ошибку: poptimizer.data.adapters.html.description.ParserError: На странице нет таблицы 2

если я правильно понял, это страница с датами закрытия реестров на московской бирже
страница начитывается, но в ней нет таблиц

приложил объекты, которые передаются в метод  _get_table_from_html
[html.txt](https://github.com/WLM1ke/poptimizer/files/8007811/html.txt)
table_num = {int} 2

[soup.txt](https://github.com/WLM1ke/poptimizer/files/8007813/soup.txt)



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/evolve/__init__.py", line 2, in <module>
    from poptimizer.evolve.evolve import Evolution
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/evolve/evolve.py", line 11, in <module>
    from poptimizer.data.views import listing
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/views/listing.py", line 8, in <module>
    from poptimizer.data.app import bootstrap, viewers
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/app/bootstrap.py", line 47, in <module>
    BUS, VIEWER = start_app()
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/app/bootstrap.py", line 42, in start_app
    bus.handle_event(event)
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/shared/app.py", line 74, in handle_event
    loop.run_until_complete(self._handle_event(event))
  File "/Users/opt/miniconda3/envs/torch39_20220205/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/shared/app.py", line 89, in _handle_event
    pending |= self._create_tasks(task.result())
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/shared/app.py", line 100, in _handle_one_command
    return await self._event_handler.handle_event(event, repo)
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/domain/handlers.py", line 69, in trading_day_ended
    *itertools.chain.from_iterable(await asyncio.gather(*aws)),
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/domain/handlers.py", line 29, in _load_by_id_and_handle_event
    return await table.handle_event(event)
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/domain/tables/base.py", line 71, in handle_event
    df_new = await self._prepare_df(event)
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/domain/tables/dividends.py", line 90, in _prepare_df
    dfs = [await gw() for gw in self._gateways]
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/domain/tables/dividends.py", line 90, in <listcomp>
    dfs = [await gw() for gw in self._gateways]
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/adapters/gateways/moex_status.py", line 57, in __call__
    df = await parser.get_df_from_url(URL, TABLE_INDEX, cols_desc)
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/adapters/html/parser.py", line 87, in get_df_from_url
    return get_df_from_html(html, table_num, cols_desc)
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/adapters/html/parser.py", line 78, in get_df_from_html
    table = _get_table_from_html(html, table_num)
  File "/Users/Documents/PythonProjects/poptimizer/poptimizer/poptimizer/data/adapters/html/parser.py", line 35, in _get_table_from_html
    raise description.ParserError(f"На странице нет таблицы {table_num}")
poptimizer.data.adapters.html.description.ParserError: На странице нет таблицы 2

**Comment by WLM1ke** [comment]
Уже в #102 сообщили - думаю это временный глюк на стороне MOEX (утром у меня все скачалось, а сейчас страница пустая). Нужно подождать, пока они у себя починят.

**Comment by ArjaraGit** [comment]
@WLM1ke, упс, не видел
ок. спасибо))

**Comment by WLM1ke** [comment]
Вроде на MOEX все починилось
