### ISSUE TITLE
проблема загрузки данных https://www.moex.com/ru/listing/listing-register-closing.aspx

### ISSUE THREAD

**Issue by swpman** [WLM1ke/poptimizer#102]
Загрузка данных по торговым дням
Сохранение ID(package='data', group='trading_dates', name='trading_dates')
TradingDayEnded(date=datetime.date(2022, 2, 4))
Загрузка инфляции
Загрузка данных
Загрузка данных
(2022-02-04, 2022-02-04)
Загрузка данных
Сохранение ID(package='data', group='usd', name='usd')
Сохранение ID(package='data', group='risk_free', name='risk_free')
Сохранение ID(package='data', group='CPI', name='CPI')
Traceback (most recent call last):
  File "%PATH_TO%\poptimizer\poptimizer\data\adapters\html\parser.py", line 33, in _get_table_from_html
    table = soup.find_all("table")[table_num]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PythonProjects\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\PythonProjects\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "%PATH_TO%\poptimizer\poptimizer\__main__.py", line 7, in <module>
    from poptimizer.data.views import div_status
  File "%PATH_TO%\poptimizer\poptimizer\data\views\div_status.py", line 10, in <module>
    from poptimizer.data.app import bootstrap, viewers
  File "%PATH_TO%\poptimizer\poptimizer\data\app\bootstrap.py", line 47, in <module>
    BUS, VIEWER = start_app()
  File "%PATH_TO%\poptimizer\poptimizer\data\app\bootstrap.py", line 42, in start_app
    bus.handle_event(event)
  File "%PATH_TO%\poptimizer\poptimizer\shared\app.py", line 74, in handle_event
    loop.run_until_complete(self._handle_event(event))
  File "D:\PythonProjects\anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "%PATH_TO%\poptimizer\poptimizer\shared\app.py", line 89, in _handle_event
    pending |= self._create_tasks(task.result())
  File "%PATH_TO%\poptimizer\poptimizer\shared\app.py", line 100, in _handle_one_command
    return await self._event_handler.handle_event(event, repo)
  File "%PATH_TO%\poptimizer\poptimizer\data\domain\handlers.py", line 69, in trading_day_ended
    *itertools.chain.from_iterable(await asyncio.gather(*aws)),
  File "%PATH_TO%\poptimizer\poptimizer\data\domain\handlers.py", line 29, in _load_by_id_and_handle_event
    return await table.handle_event(event)
  File "%PATH_TO%\poptimizer\poptimizer\data\domain\tables\base.py", line 71, in handle_event
    df_new = await self._prepare_df(event)
  File "%PATH_TO%\poptimizer\poptimizer\data\domain\tables\dividends.py", line 90, in _prepare_df
    dfs = [await gw() for gw in self._gateways]
  File "%PATH_TO%\poptimizer\poptimizer\data\domain\tables\dividends.py", line 90, in <listcomp>
    dfs = [await gw() for gw in self._gateways]
  File "%PATH_TO%\poptimizer\poptimizer\data\adapters\gateways\moex_status.py", line 57, in __call__
    df = await parser.get_df_from_url(URL, TABLE_INDEX, cols_desc)
  File "%PATH_TO%\poptimizer\poptimizer\data\adapters\html\parser.py", line 87, in get_df_from_url
    return get_df_from_html(html, table_num, cols_desc)
  File "%PATH_TO%\poptimizer\poptimizer\data\adapters\html\parser.py", line 78, in get_df_from_html
    table = _get_table_from_html(html, table_num)
  File "%PATH_TO%\poptimizer\poptimizer\data\adapters\html\parser.py", line 35, in _get_table_from_html
    raise description.ParserError(f"На странице нет таблицы {table_num}")
poptimizer.data.adapters.html.description.ParserError: На странице нет таблицы 2

Видимо что то поменяли...

**Comment by WLM1ke** [comment]
Видимо глюк на стороне MOEX -  страничка [пустая](https://www.moex.com/ru/listing/listing-register-closing.aspx).

**Comment by WLM1ke** [comment]
Вроде на MOEX все починилось

**Comment by swpman** [comment]
Да, все загрузилось. Спасибо.
