### ISSUE TITLE
Деление на ноль - ver2

### ISSUE THREAD

**Issue by michael-xiii** [WLM1ke/poptimizer#118]
Вот пока остановился, нужно дебажить, пока мозг другим занят, может позже смогу

`Родитель - новый организм:
LLH — -
RET — -
Timer — 0:00:00 / Scores - 0
Data: {'batch_size': 156.69872975649423, 'history_days': 252.0351517922407, 'ticker_on': -0.6730522648346267, 'day_of_year_on': -0.1605870814360828, 'day_of_period_on': 0.21682183519577292, 'prices_on': 0.762300208793548, 'dividends_on': -0.8097435771820718, 'turnover_on': 0.5171080757143744, 'average_turnover_on': 0.6785819515625062, 'rvi_on': -0.22259955455775748, 'mcftrr_on': -0.9192450152044622, 'imoex_on': -0.4139772375192172, 'ticker_type_on': 0.9659468101259128, 'usd_on': 0.17421703248732245, 'open_on': -0.43721215980049877, 'high_on': -0.3784744732591283, 'low_on': -0.6105872745790679, 'meogtrr_on': -0.4820343532516377}
Model: {'start_bn': -0.831421892115181, 'kernels': 7.334334884499653, 'sub_blocks': 1.5426032220953156, 'gate_channels': 5.465127735687826, 'residual_channels': 5.429110332503992, 'skip_channels': 6.874305627000521, 'end_channels': 4.612931300201867, 'mixture_size': 2.59582732852365}
Optimizer: {'betas': 0.9990014465411454, 'eps': 3.700845116648455e-08, 'weight_decay': 0.09309466492746882}
Scheduler: {'max_lr': 0.004312645003500621, 'epochs': 2.669850453284494, 'pct_start': 0.29962133517006645, 'anneal_strategy': -0.7838951497431939, 'base_momentum': 0.849365335366552, 'max_momentum': 0.9495491413628193, 'div_factor': 293.4545068509862, 'final_div_factor': 87517.41194504395}
Utility: {'max_std': 0.13538762956131553}

DateCheckRequired(timestamp=datetime.datetime(2022, 12, 10, 8, 25, 21, 682434))
Удаляю - Слишком большая длинна истории - 252

DateCheckRequired(timestamp=datetime.datetime(2022, 12, 10, 8, 25, 37, 78626))
***2022-12-09: Шаг эволюции — 51***
LLH - (-, -, -)
RET - (-, -, -)
Организмов - 0 / Максимум оценок - 0
Traceback (most recent call last):

  File "/Users/xxx/.pyenv/versions/3.10.8/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,

  File "/Users/xxx.pyenv/versions/3.10.8/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)

  File "/Users/xxx/src/poptimizer/poptimizer/__main__.py", line 48, in <module>
    app(prog_name="poptimizer")

  File "/Users/xxx/src/poptimizer/poptimizer/__main__.py", line 17, in evolve
    ev.evolve()

  File "/Users/xxx/src/poptimizer/poptimizer/evolve/evolve.py", line 68, in evolve
    self._logger.info(f"Тестов - {self._tests}\n")

  File "/Users/xxx/src/poptimizer/poptimizer/evolve/evolve.py", line 41, in _tests
    bound = seq.minimum_bounding_n(config.P_VALUE / count)

ZeroDivisionError: float division by zero

make: *** [run_evolve] Error 1
`

**Comment by WLM1ke** [comment]
У вас просто все организмы померли. В чем причина не знаю, возможно вы каких-то странных не дефолтных бумаг накидали в портфель. Чтобы понять нужен состав портфеля.

**Comment by WLM1ke** [comment]
Текстом лучше здесь. Если есть необходимость, то можно голосом через телегу @WLMike

**Comment by WLM1ke** [comment]
Возьмите дефолтный [портфель](https://github.com/WLM1ke/poptimizer/blob/version_2/portfolio/base.yaml) для начала. Если у вас есть какие-то бумаги, которых в нем нет, добавьте, но если они реально торгуются.

У вас много очень странных бумаг, которые реально не торгуются - смысла их добавлять нет.

**Comment by Snest1** [comment]
Коллеги, а разве комменты в yaml можно делать?

**Comment by WLM1ke** [comment]
@Snest1 да
