### ISSUE TITLE
Редкая ошибка: TypeError: '<' not supported between instances of 'complex' and 'float'

### ISSUE THREAD

**Issue by Snest1** [WLM1ke/poptimizer#121]
Добрый день.

В редких случаях возникает ошибка:

~~> Test: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 84.65it/s, 2.82811]
Traceback (most recent call last):
  File "/home/sn/sn/poptimizer/poptimizer/evolve/evolve.py", line 219, in evolve
    org = self._step(org)
  File "/home/sn/sn/poptimizer/poptimizer/evolve/evolve.py", line 271, in _step
    if (margin := self._eval_organism(hunter)) is None:
  File "/home/sn/sn/poptimizer/poptimizer/evolve/evolve.py", line 322, in _eval_organism
    organism.evaluate_fitness(self._tickers, date)
  File "/home/sn/sn/poptimizer/poptimizer/evolve/population.py", line 131, in evaluate_fitness
    llh, ir = model.quality_metrics
  File "/home/sn/sn/poptimizer/poptimizer/dl/model.py", line 123, in quality_metrics
    self._llh = self._eval_llh()
  File "/home/sn/sn/poptimizer/poptimizer/dl/model.py", line 211, in _eval_llh
    ir = _opt_port(
  File "/home/sn/sn/poptimizer/poptimizer/dl/model.py", line 402, in _opt_port
    w, sigma = _opt_weight(mean, var, tickers, end, phenotype)
  File "/home/sn/sn/poptimizer/poptimizer/dl/model.py", line 483, in _opt_weight
    rez = optimize.minimize(
  File "/home/sn/sn/poptimizer/.venv/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 705, in minimize
    res = _minimize_slsqp(fun, x0, args, jac, bounds,
  File "/home/sn/sn/poptimizer/.venv/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py", line 428, in _minimize_slsqp
    fx = wrapped_fun(x)
  File "/home/sn/sn/poptimizer/.venv/lib/python3.10/site-packages/scipy/optimize/_optimize.py", line 346, in eval
    return func(x)
  File "/home/sn/sn/poptimizer/.venv/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 267, in fun
    self._update_fun()
  File "/home/sn/sn/poptimizer/.venv/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 251, in _update_fun
    self._update_fun_impl()
  File "/home/sn/sn/poptimizer/.venv/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 155, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/sn/sn/poptimizer/.venv/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 148, in fun_wrapped
    if fx < self._lowest_f:
TypeError: '<' not supported between instances of 'complex' and 'float'

**Comment by WLM1ke** [comment]
Есть подозрение, что это баг в scipy - поставлю перехват ошибки.
