### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by RomaKoks** [WLM1ke/poptimizer#49]
Потомок:
Побед - 0
Data: {'batch_size': 204.9562127867058, 'history_days': 3.3102549152105727, 'ticker_on': -5776.724982106083, 'day_of_year_on': -1780.9273236372533, 'day_of_period_on': -13489.714181493244, 'prices_on': -30336.533005284495, 'dividends_on': -548625.4968190438, 'turnover_on': -397529.18654028786, 'average_turnover_on': -1324596.296612373, 'rvi_on': -954.3014412478325, 'mcftrr_on': -0.5122750395318638}
Model: {'start_bn': -580395.1587646941, 'kernels': 3.538092510358175, 'sub_blocks': 1.191626480806004, 'gate_channels': 294.91508063470513, 'residual_channels': 145.71541125887177, 'skip_channels': 135.19470189097453, 'end_channels': 201.1516020489509}
Optimizer: {'betas': 0.9893778147420297, 'eps': 2.735814118142896e-07, 'weight_decay': 0.49070839808123856, 'amsgrad': -258547.40207594028}
Scheduler: {'max_lr': 0.007796431125684897, 'epochs': 8.460116105978639, 'pct_start': 0.35364452023660325, 'anneal_strategy': -29558.046276696186, 'base_momentum': 0.9862028678552708, 'max_momentum': 0.5580588206266746, 'div_factor': 365.9928552054215, 'final_div_factor': 25411.010159529764}
Количество слоев - 30
Количество параметров - 769546
Epochs - 8.46
Train size - 189826
~~> Train:   0%|          | 0/7877 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/user_name/PycharmProjects/poptimizer/poptimizer/__main__.py", line 19, in evolve
    ev.evolve(port)
  File "/home/user_name/PycharmProjects/poptimizer/poptimizer/evolve/evolve.py", line 56, in evolve
    child_fitness = self._eval_and_print(child, tickers, end)
  File "/home/user_name/PycharmProjects/poptimizer/poptimizer/evolve/evolve.py", line 84, in _eval_and_print
    fitness = organism.evaluate_fitness(tickers, end)
  File "/home/user_name/PycharmProjects/poptimizer/poptimizer/evolve/population.py", line 76, in evaluate_fitness
    llh = model.llh
  File "/home/user_name/PycharmProjects/poptimizer/poptimizer/dl/model.py", line 104, in llh
    self._llh = self._eval_llh()
  File "/home/user_name/PycharmProjects/poptimizer/poptimizer/dl/model.py", line 123, in _eval_llh
    model = self.get_model(loader)
  File "/home/user_name/PycharmProjects/poptimizer/poptimizer/dl/model.py", line 159, in get_model
    self._model = self._train_model()
  File "/home/user_name/PycharmProjects/poptimizer/poptimizer/dl/model.py", line 229, in _train_model
    output = model(batch)
  File "/home/user_name/anaconda3/envs/finan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user_name/PycharmProjects/poptimizer/poptimizer/dl/models/wave_net.py", line 273, in forward
    y, skip = block(y)
  File "/home/user_name/anaconda3/envs/finan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user_name/PycharmProjects/poptimizer/poptimizer/dl/models/wave_net.py", line 121, in forward
    y = sub_block(y)
  File "/home/user_name/anaconda3/envs/finan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user_name/PycharmProjects/poptimizer/poptimizer/dl/models/wave_net.py", line 51, in forward
    y_signal = self.signal_conv(y)
  File "/home/user_name/anaconda3/envs/finan/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user_name/anaconda3/envs/finan/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 256, in forward
    return F.conv1d(input, self.weight, self.bias, self.stride,
RuntimeError: Given groups=1, weight of size [294, 145, 3], expected input[1, 1, 3] to have 145 channels, but got 1 channels instead

**Comment by WLM1ke** [comment]
Понятная ошибка - модель без признаков. Постараюсь исправить.
