### ISSUE TITLE
CPIGatewayError: На странице отсутствует ссылка на страницу с потребительской инфляцией

### ISSUE THREAD

**Issue by RomaKoks** [WLM1ke/poptimizer#54]
Получил такую ошибку. Стал смотреть, пришел к этой строчке:
https://github.com/WLM1ke/poptimizer/blob/50ef83c40e85ee4440d67e23aca30786cbbf6317/poptimizer/data/adapters/gateways/cpi.py#L15
В ней все правильно? Я зашел на страницу https://rosstat.gov.ru/price , по которой идёт поиск, и в коде страницы была ссылка:
/storage/mediabank/Rm1nIXsH/Индексы потребительских цен.htm
но она не походит под регулярку в указанной строке.
Лог:
{"t":{"$date":"2021-04-09T14:41:37.316+03:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
{"t":{"$date":"2021-04-09T14:41:37.588+03:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2021-04-09T14:41:37.588+03:00"},"s":"I",  "c":"NETWORK",  "id":4648602, "ctx":"main","msg":"Implicit TCP FastOpen in use."}
{"t":{"$date":"2021-04-09T14:41:37.589+03:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":18084,"port":27017,"dbPath":"PATH_TO/poptimizer/db","architecture":"64-bit","host":"iRU"}}
{"t":{"$date":"2021-04-09T14:41:37.589+03:00"},"s":"I",  "c":"CONTROL",  "id":23398,   "ctx":"initandlisten","msg":"Target operating system minimum version","attr":{"targetMinOS":"Windows 7/Windows Server 2008 R2"}}
{"t":{"$date":"2021-04-09T14:41:37.589+03:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.0","gitVersion":"563487e100c4215e2dce98d0af2a6a5a2d67c5cf","modules":[],"allocator":"tcmalloc","environment":{"distmod":"windows","distarch":"x86_64","target_arch":"x86_64"}}}}
{"t":{"$date":"2021-04-09T14:41:37.589+03:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Microsoft Windows 10","version":"10.0 (build 19042)"}}}
{"t":{"$date":"2021-04-09T14:41:37.589+03:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"localhost"},"storage":{"dbPath":"PATH_TO\\poptimizer\\db","directoryPerDB":true}}}}
{"t":{"$date":"2021-04-09T14:41:37.591+03:00"},"s":"E",  "c":"STORAGE",  "id":20557,   "ctx":"initandlisten","msg":"DBException in initAndListen, terminating","attr":{"error":"DBPathInUse: Unable to create/open the lock file: PATH_TO\\poptimizer\\db\\mongod.lock (Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.). Ensure the user executing mongod is the owner of the lock file and has the appropriate permissions. Also make sure that another mongod instance is not already running on the PATH_TO\\poptimizer\\db directory"}}
{"t":{"$date":"2021-04-09T14:41:37.591+03:00"},"s":"I",  "c":"NETWORK",  "id":20562,   "ctx":"initandlisten","msg":"Shutdown: going to close listening sockets"}
{"t":{"$date":"2021-04-09T14:41:37.591+03:00"},"s":"I",  "c":"-",        "id":20520,   "ctx":"initandlisten","msg":"Stopping further Flow Control ticket acquisitions."}
{"t":{"$date":"2021-04-09T14:41:37.591+03:00"},"s":"I",  "c":"CONTROL",  "id":20565,   "ctx":"initandlisten","msg":"Now exiting"}
{"t":{"$date":"2021-04-09T14:41:37.591+03:00"},"s":"I",  "c":"CONTROL",  "id":23138,   "ctx":"initandlisten","msg":"Shutting down","attr":{"exitCode":100}}
2021-04-09T14:41:38.252+0300	preparing collections to restore from
2021-04-09T14:41:38.277+0300	reading metadata for source.dividends from PATH_TO\poptimizer\dump\source\dividends.metadata.json
2021-04-09T14:41:38.484+0300	restoring source.dividends from PATH_TO\poptimizer\dump\source\dividends.bson
2021-04-09T14:41:38.494+0300	restoring indexes for collection source.dividends from metadata
2021-04-09T14:41:38.812+0300	finished restoring source.dividends (841 documents, 0 failures)
2021-04-09T14:41:38.812+0300	841 document(s) restored successfully. 0 document(s) failed to restore.
2021-04-09T14:41:39.770+0300	writing source.dividends to PATH_TO\poptimizer\dump\source\dividends.bson
2021-04-09T14:41:39.790+0300	done dumping source.dividends (841 documents)
Traceback (most recent call last):
  File "PATH_TO\poptimizer\loop.py", line 6, in <module>
    from poptimizer.__main__ import evolve, optimize
  File "PATH_TO\poptimizer\poptimizer\__main__.py", line 9, in <module>
    from poptimizer.data.views import div_status, listing
  File "PATH_TO\poptimizer\poptimizer\data\views\div_status.py", line 9, in <module>
    from poptimizer.data.app import bootstrap, viewers
  File "PATH_TO\poptimizer\poptimizer\data\app\bootstrap.py", line 47, in <module>
    BUS, VIEWER = start_app()
  File "PATH_TO\poptimizer\poptimizer\data\app\bootstrap.py", line 42, in start_app
    bus.handle_event(event)
  File "PATH_TO\poptimizer\poptimizer\shared\app.py", line 69, in handle_event
    loop.run_until_complete(self._handle_event(event))
  File "C:\Users\tokar\anaconda3\envs\finan\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "PATH_TO\poptimizer\poptimizer\shared\app.py", line 81, in _handle_event
    pending |= self._create_tasks(task.result())
  File "PATH_TO\poptimizer\poptimizer\shared\app.py", line 92, in _handle_one_command
    return await self._event_handler.handle_event(event, repo)
  File "PATH_TO\poptimizer\poptimizer\data\domain\handlers.py", line 68, in trading_day_ended
    *itertools.chain.from_iterable(await asyncio.gather(*aws)),
  File "PATH_TO\poptimizer\poptimizer\data\domain\handlers.py", line 29, in _load_by_id_and_handle_event
    return await table.handle_event(event)
  File "PATH_TO\poptimizer\poptimizer\data\domain\tables\base.py", line 71, in handle_event
    df_new = await self._prepare_df(event)
  File "PATH_TO\poptimizer\poptimizer\data\domain\tables\cpi.py", line 32, in _prepare_df
    return await self._gateway()
  File "PATH_TO\poptimizer\poptimizer\data\adapters\gateways\cpi.py", line 104, in __call__
    df = await _load_xlsx(self._session)
  File "PATH_TO\poptimizer\poptimizer\data\adapters\gateways\cpi.py", line 59, in _load_xlsx
    file_url = await _get_xlsx_url(session)
  File "PATH_TO\poptimizer\poptimizer\data\adapters\gateways\cpi.py", line 49, in _get_xlsx_url
    cpi_url = await _get_cpi_url(session)
  File "PATH_TO\poptimizer\poptimizer\data\adapters\gateways\cpi.py", line 44, in _get_cpi_url
    raise CPIGatewayError("На странице отсутствует ссылка на страницу с потребительской инфляцией")
poptimizer.data.adapters.gateways.cpi.CPIGatewayError: На странице отсутствует ссылка на страницу с потребительской инфляцией

**Comment by WLM1ke** [comment]
@RomaKoks утром ее получил (пути на сайте изменились) и вроде уже исправил в последней версии. Только что запушил

**Comment by RomaKoks** [comment]
Понял, спасибо!
