### ISSUE TITLE
Ошибка в процессе обучения моделей

### ISSUE THREAD

**Issue by YoukaiCat** [WLM1ke/poptimizer#56]
После обновления evolve аварийно завершается с трейсом:
```
Traceback (most recent call last):
File "/home/parsee/poptimizer/poptimizer/evolve/store.py", line 48, in __get__
return data_dict[self._name]
KeyError: 'llh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/parsee/poptimizer/./poptimizer/__main__.py", line 44, in <module>
app(prog_name="poptimizer")
File "/home/parsee/miniconda3/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
return get_command(self)(*args, **kwargs)
File "/home/parsee/miniconda3/lib/python3.9/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/home/parsee/miniconda3/lib/python3.9/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/home/parsee/miniconda3/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/parsee/miniconda3/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/parsee/miniconda3/lib/python3.9/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/home/parsee/miniconda3/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
return callback(**use_params)  # type: ignore
File "/home/parsee/poptimizer/./poptimizer/__main__.py", line 19, in evolve
ev.evolve(port)
File "/home/parsee/poptimizer/poptimizer/evolve/evolve.py", line 67, in evolve
_kill_weakest(child)
File "/home/parsee/poptimizer/poptimizer/evolve/evolve.py", line 114, in _kill_weakest
print(f"LLH: {weakest.llh:.4f}")
File "/home/parsee/poptimizer/poptimizer/evolve/population.py", line 63, in llh
return self._doc.llh
File "/home/parsee/poptimizer/poptimizer/evolve/store.py", line 50, in __get__
raise AttributeError(f"'{owner.__name__}' object has no attribute {error}")
AttributeError: 'Doc' object has no attribute 'llh'
```

Полный лог: https://gist.github.com/YoukaiCat/b3ef8830ad0241c7d1bbfabea4367047
Воспроизводится на master ветке без каких-либо моих изменений.

**Comment by WLM1ke** [comment]
@YoukaiCat Вы в первый раз запускаете?

**Comment by WLM1ke** [comment]
Пофиксил в последней версии

**Comment by YoukaiCat** [comment]
Спасибо! На e2d0307 всё работает.
