### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by AlexQww** [WLM1ke/poptimizer#60]
Потомок:
Побед — 0
Data: {'batch_size': 177.7385721058952, 'history_days': 55.70134040397355, 'ticker_on': -90.52231354907431, 'day_of_year_on': 10.266435523458313, 'day_of_period_on': -59.75439292031155, 'prices_on': 464.5733644522056, 'dividends_on': -6.221069051894889, 'turnover_on': 0.6707214118303866, 'average_turnover_on': -64.84367367009655, 'rvi_on': 451.557234503783, 'mcftrr_on': 5.060442543491146, 'imoex_on': -2605.016051899486, 'ticker_type_on': 426.15916544317963, 'usd_on': -17.02749236435758, 'open_on': 36.30055136508749, 'high_on': 41.832617063123394, 'low_on': -42.290686709031405}
Model: {'start_bn': 3.68131633535158, 'kernels': 1.8169208373228016, 'sub_blocks': 1.172485135834774, 'gate_channels': 9.603954794985695, 'residual_channels': 14.822437221051137, 'skip_channels': 21.963910979579275, 'end_channels': 23.69156068767206, 'mixture_size': 12.36557598230185}
Optimizer: {'betas': 0.998975098900571, 'eps': 6.043738817960838e-09, 'weight_decay': 0.017549188685557042}
Scheduler: {'max_lr': 0.026301493988270034, 'epochs': 0.975965210378401, 'pct_start': 0.2750600642864314, 'anneal_strategy': -58.68592289332554, 'base_momentum': 0.6260647115426332, 'max_momentum': 0.7563211017511952, 'div_factor': 23.49088257256306, 'final_div_factor': 885334.0228427305}
Количество слоев - 74
Количество параметров - 13761
Epochs - 0.98
Train size - 197585
~~> Train:  27%|████████████████████████                                                                 | 295/1091 [00:13<00:35, 22.13it/s, -0.22357]
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/torchok/PycharmProjects/poptimizer/poptimizer/__main__.py", line 158, in <module>
    app(prog_name="poptimizer")
  File "/home/torchok/PycharmProjects/poptimizer/venv/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/torchok/PycharmProjects/poptimizer/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/torchok/PycharmProjects/poptimizer/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/torchok/PycharmProjects/poptimizer/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/torchok/PycharmProjects/poptimizer/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/torchok/PycharmProjects/poptimizer/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/torchok/PycharmProjects/poptimizer/venv/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/torchok/PycharmProjects/poptimizer/poptimizer/__main__.py", line 17, in evolve
    ev.evolve()
  File "/home/torchok/PycharmProjects/poptimizer/poptimizer/evolve/evolve.py", line 76, in evolve
    if _eval_and_print(child, tickers, end) is None:
  File "/home/torchok/PycharmProjects/poptimizer/poptimizer/evolve/evolve.py", line 112, in _eval_and_print
    fitness = organism.evaluate_fitness(tickers, end)
  File "/home/torchok/PycharmProjects/poptimizer/poptimizer/evolve/population.py", line 83, in evaluate_fitness
    llh, ir = model.quality_metrics
  File "/home/torchok/PycharmProjects/poptimizer/poptimizer/dl/model.py", line 114, in quality_metrics
    self._llh = self._eval_llh()
  File "/home/torchok/PycharmProjects/poptimizer/poptimizer/dl/model.py", line 148, in _eval_llh
    model = self.prepare_model(loader)
  File "/home/torchok/PycharmProjects/poptimizer/poptimizer/dl/model.py", line 126, in prepare_model
    self._model = self._train_model()
  File "/home/torchok/PycharmProjects/poptimizer/poptimizer/dl/model.py", line 258, in _train_model
    loss, means, _ = loss_fn(model, batch)
  File "/home/torchok/PycharmProjects/poptimizer/poptimizer/dl/model.py", line 62, in log_normal_llh_mix
    dist = model.dist(batch)
  File "/home/torchok/PycharmProjects/poptimizer/poptimizer/dl/models/wave_net.py", line 318, in dist
    weights_dist = distributions.Categorical(logits=logits)
  File "/home/torchok/PycharmProjects/poptimizer/venv/lib/python3.9/site-packages/torch/distributions/categorical.py", line 64, in __init__
    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
  File "/home/torchok/PycharmProjects/poptimizer/venv/lib/python3.9/site-packages/torch/distributions/distribution.py", line 53, in __init__
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter logits has invalid values

**Comment by WLM1ke** [comment]
А какая версия PyTorch у вас стоит?

**Comment by AlexQww** [comment]
1.8.1+cu102

**Comment by WLM1ke** [comment]
Поставьте 1.9. Про CuDa не знаю какая последняя, но тоже желательно обновить.

**Comment by AlexQww** [comment]
После обновления pytorch и последней версии оптимизатора теперь сваливается с таким

**Comment by WLM1ke** [comment]
Нужна последняя версия scipy

**Comment by AlexQww** [comment]
Спасибо, помогло
