### ISSUE TITLE
evolve: unexpected keyword argument 'permutations'

### ISSUE THREAD

**Issue by YoukaiCat** [WLM1ke/poptimizer#61]
После обновления перестала работать эволюция.
Выводит  трейс:
```
Родитель нападает на добычу:
Traceback (most recent call last):
File "/home/parsee/poptimizer/./poptimizer/__main__.py", line 37, in <module>
app(prog_name="poptimizer")
File "/home/parsee/miniconda3/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
return get_command(self)(*args, **kwargs)
File "/home/parsee/miniconda3/lib/python3.9/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/home/parsee/miniconda3/lib/python3.9/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/home/parsee/miniconda3/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/parsee/miniconda3/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/parsee/miniconda3/lib/python3.9/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/home/parsee/miniconda3/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
return callback(**use_params)  # type: ignore
File "/home/parsee/poptimizer/./poptimizer/__main__.py", line 12, in evolve
ev.evolve()
File "/home/parsee/poptimizer/poptimizer/evolve/evolve.py", line 70, in evolve
if self._prey_killed(parent, prey):
File "/home/parsee/poptimizer/poptimizer/evolve/evolve.py", line 148, in _prey_killed
_, p_value = stats.ttest_ind(
TypeError: ttest_ind() got an unexpected keyword argument 'permutations'
```

Полный лог: https://gist.github.com/YoukaiCat/a31a1acabb877f66c6880cc452aab9c0

**Comment by WLM1ke** [comment]
Нужна последняя версия scipy

**Comment by YoukaiCat** [comment]
Спасибо! Теперь работает.
