### ISSUE TITLE
Нужна обработка слишком большого history_days в результате эволюции

### ISSUE THREAD

**Issue by RomaKoks** [WLM1ke/poptimizer#69]
````
***2021-11-12: Шаг эволюции — 265***
LLH - (0.8711, 2.7421, 2.8299)
RET - (0.0533, 0.2857, 0.9786)
Организмов - 109 / Максимум оценок - 9
Доля принятых - 24.38%

Родитель:
LLH — 1.0599: 1.0878, 1.0499, 1.0321, 1.0360, 1.0724, 1.0739, 1.0629, 1.0702, 1.0543
RET — 0.3209: 0.2983, 0.3431, 0.5413, 0.4155, 0.3248, 0.2233, 0.2299, 0.2680, 0.2444
Timer — 0:01:35
Data: {'batch_size': 12538.909770179394, 'history_days': 206.6340404114518, 'ticker_on': -27.851100142615003, 'day_of_year_on': 3.003903146391359, 'day_of_period_on': 0.09298512564162972, 'prices_on': -1.2356011287782966, 'dividends_on': 5.281168692071963, 'turnover_on': 1097.6412588906178, 'average_turnover_on': -137.31812095042886, 'rvi_on': 1.1394448984646637, 'mcftrr_on': -1035.7671194581624, 'imoex_on': 16.451081354972647, 'ticker_type_on': -18.88785381132009, 'usd_on': 5.053386319673658, 'open_on': 18.628071609078365, 'high_on': -1.2838003948298191, 'low_on': 2.6327172181399794, 'meogtrr_on': 0.7555408299677332}
Model: {'start_bn': -6.106530253047609, 'kernels': 7.849879889206337, 'sub_blocks': 32.269481480168096, 'gate_channels': 13.361194742689179, 'residual_channels': 29.013755026884443, 'skip_channels': 4.485923773196008, 'end_channels': 3.6420667744873283, 'mixture_size': 23.769801352687686}
Optimizer: {'betas': 0.9989989792474319, 'eps': 2.69744865890668e-07, 'weight_decay': 0.37832394878427655}
Scheduler: {'max_lr': 0.5123636051185311, 'epochs': 0.034064066207938615, 'pct_start': 0.2992583930527831, 'anneal_strategy': 45.911779177450235, 'base_momentum': 0.7847317605834427, 'max_momentum': 0.949193175241471, 'div_factor': 1131.6321634466094, 'final_div_factor': 72315.14651363067} 

Претендент - новый организм:
LLH — -
RET — -
Timer — 0:00:00
Data: {'batch_size': 12536.307453788919, 'history_days': 3768.612053130967, 'ticker_on': -27.8251336605893, 'day_of_year_on': 2.679672921571562, 'day_of_period_on': 0.07587551758791003, 'prices_on': -1.4444338554680354, 'dividends_on': 5.196017516980653, 'turnover_on': 1097.9431317010308, 'average_turnover_on': -141.3313656829068, 'rvi_on': 0.2803152984240963, 'mcftrr_on': -1035.737567150942, 'imoex_on': 16.464444571137232, 'ticker_type_on': -18.918861238789756, 'usd_on': 5.680644606399607, 'open_on': 18.587368984726588, 'high_on': -2.4609938002982825, 'low_on': 2.640818152018767, 'meogtrr_on': 0.8090094396211781}
Model: {'start_bn': -6.124026519955858, 'kernels': 7.779952469628877, 'sub_blocks': 32.31421098039613, 'gate_channels': 13.008014694168885, 'residual_channels': 28.991498992916597, 'skip_channels': 4.3918872007842875, 'end_channels': 3.6027284114052383, 'mixture_size': 23.806811571271666}
Optimizer: {'betas': 0.9989989192911831, 'eps': 2.595997674257352e-07, 'weight_decay': 0.3915807080445315}
Scheduler: {'max_lr': 0.5120581350534901, 'epochs': 0.01341430924179389, 'pct_start': 0.2990725920166547, 'anneal_strategy': 45.39829535425662, 'base_momentum': 0.7845912285044897, 'max_momentum': 0.9492807641264684, 'div_factor': 1150.6293052367987, 'final_div_factor': 77950.93505920934} 

INFO:EventBus:DateCheckRequired(timestamp=datetime.datetime(2021, 11, 14, 5, 18, 45, 827478))
num_samples should be a positive integer value, but got num_samples=0
Traceback (most recent call last):
  File "PATH_TO/poptimizer/loop.py", line 10, in <module>
    evolve()
  File "PATH_TO/poptimizer/poptimizer/__main__.py", line 12, in evolve
    ev.evolve()
  File "PATH_TO/poptimizer/poptimizer/evolve/evolve.py", line 58, in evolve
    next_, new = self._step(current)
  File "PATH_TO/poptimizer/poptimizer/evolve/evolve.py", line 130, in _step
    if self._eval_organism(prey) is None:
  File "PATH_TO/poptimizer/poptimizer/evolve/evolve.py", line 178, in _eval_organism
    organism.evaluate_fitness(self._tickers, date)
  File "PATH_TO/poptimizer/poptimizer/evolve/population.py", line 117, in evaluate_fitness
    llh, ir = model.quality_metrics
  File "PATH_TO/poptimizer/poptimizer/dl/model.py", line 106, in quality_metrics
    self._llh = self._eval_llh()
  File "PATH_TO/poptimizer/poptimizer/dl/model.py", line 140, in _eval_llh
    model = self.prepare_model(loader)
  File "PATH_TO/poptimizer/poptimizer/dl/model.py", line 118, in prepare_model
    self._model = self._train_model()
  File "PATH_TO/poptimizer/poptimizer/dl/model.py", line 202, in _train_model
    loader = data_loader.DescribedDataLoader(
  File "PATH_TO/poptimizer/poptimizer/dl/data_loader.py", line 68, in __init__
    super().__init__(
  File "PATH_TO/anaconda3/envs/finan/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 268, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "PATH_TO/anaconda3/envs/finan/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 102, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
````

**Comment by WLM1ke** [comment]
Интересная ситуация - сделаю.
