### ISSUE TITLE
Оптимизация выдает ошибку

### ISSUE THREAD

**Issue by swpman** [WLM1ke/poptimizer#83]
INFO:Config:{'P_VALUE': 0.05, 'FORECAST_DAYS': 21, 'HISTORY_DAYS_MIN': 63, 'TARGET_POPULATION': 100, 'START_EVOLVE_HOUR': 1, 'STOP_EVOLVE_HOUR': 1, 'COSTS': 0.025, 'MARKET_IMPACT_FACTOR': 1, 'OPTIMIZER': 'resample'}

INFO:EventBus:DateCheckRequired(timestamp=datetime.datetime(2021, 12, 2, 14, 18, 51, 211020))

Forecasts: 99it [19:11, 11.64s/it]

ПОРТФЕЛЬ [base, test] - 2021-12-01

Количество бумаг - 199

Открытых позиций - 8

Эффективных позиций - 4

           LOT_SIZE    SHARES        PRICE      VALUE    WEIGHT      TURNOVER

.
.
.

PORTFOLIO         ...........

PATH_TO/poptimizer/portfolio/metrics.py:78: RuntimeWarning: invalid value encountered in matmul

  portfolio_var = weight.reshape(1, -1) @ cov @ weight.reshape(-1, 1)  # noqa: WPS221

PATH_TO/poptimizer/portfolio/metrics.py:90: RuntimeWarning: invalid value encountered in matmul

  beta = cov @ weight.reshape(-1, 1)

КЛЮЧЕВЫЕ МЕТРИКИ ПОРТФЕЛЯ

Дней в истории - (89 <-> 146 <-> 196)

Корреляция - (7.16% <-> 8.09% <-> 8.82%)

Сжатие - (40.07% <-> 46.09% <-> 52.70%)

               MEAN       STD      BETA    R_GEOM      GRAD

AAL-RM    ...

.
.
.

CASH       ...

PORTFOLIO  ...

Консервативная доходность:  25.69%

Консервативный риск:        51.69%

Консервативная метрика:     16.23%

Оценка просадки:            36.07%

Traceback (most recent call last):

  File "PATH_TO/lib/python3.9/runpy.py", line 197, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "PATH_TO/lib/python3.9/runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "PATH_TO/poptimizer/__main__.py", line 42, in <module>

    app(prog_name="poptimizer")

  File "PATH_TO/lib/python3.9/site-packages/typer/main.py", line 214, in __call__

    return get_command(self)(*args, **kwargs)

  File "PATH_TO/lib/python3.9/site-packages/click/core.py", line 1128, in __call__

    return self.main(*args, **kwargs)

  File "PATH_TO/lib/python3.9/site-packages/click/core.py", line 1053, in main

    rv = self.invoke(ctx)

  File "PATH_TO/lib/python3.9/site-packages/click/core.py", line 1659, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "PATH_TO/lib/python3.9/site-packages/click/core.py", line 1395, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "PATH_TO/lib/python3.9/site-packages/click/core.py", line 754, in invoke

    return __callback(*args, **kwargs)

  File "PATH_TO/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper

    return callback(**use_params)  # type: ignore

  File "PATH_TO/poptimizer/__main__.py", line 31, in optimize

    print(opt)

  File "PATH_TO/poptimizer/portfolio/optimizer_resample.py", line 45, in __str__

    df = self._for_trade()

  File "PATH_TO/poptimizer/portfolio/optimizer_resample.py", line 68, in _for_trade

    conf_int = self._prepare_bounds()

  File "PATH_TO/poptimizer/portfolio/optimizer_resample.py", line 111, in _prepare_bounds

    conf_int = conf_int.apply(

  File "PATH_TO/lib/python3.9/site-packages/pandas/core/frame.py", line 8740, in apply

    return op.apply()

  File "PATH_TO/lib/python3.9/site-packages/pandas/core/apply.py", line 688, in apply

    return self.apply_standard()

  File "PATH_TO/lib/python3.9/site-packages/pandas/core/apply.py", line 812, in apply_standard

    results, res_index = self.apply_series_generator()

  File "PATH_TO/lib/python3.9/site-packages/pandas/core/apply.py", line 828, in apply_series_generator

    results[i] = self.f(v)

  File "PATH_TO/poptimizer/portfolio/optimizer_resample.py", line 112, in <lambda>

    lambda grad: _grad_conf_int(grad, p_value),

  File "PATH_TO/poptimizer/portfolio/optimizer_resample.py", line 179, in _grad_conf_int

    interval = stats.bootstrap(

  File "PATH_TO/lib/python3.9/site-packages/scipy/stats/_bootstrap.py", line 454, in bootstrap

    ci_l = percentile_fun(theta_hat_b, interval[0]*100)

  File "PATH_TO/lib/python3.9/site-packages/scipy/stats/_bootstrap.py", line 78, in _percentile_along_axis

    percentiles[indices] = np.percentile(theta_hat_b_i, alpha_i)

  File "<__array_function__ internals>", line 5, in percentile

  File "PATH_TO/lib/python3.9/site-packages/numpy/lib/function_base.py", line 3866, in percentile

    raise ValueError("Percentiles must be in the range [0, 100]")

ValueError: Percentiles must be in the range [0, 100]

**Comment by WLM1ke** [comment]
У вас нет прогнозов. Вы или не запускали эволюцию или не запускали после изменения тикеров.

**Comment by swpman** [comment]
Прогнозы есть, Эволюция работает сутки, как раз после изменения тикетов, все модели переобучились пару новых нашлось. Коллекцию forecasts удалял, но все еще выдает ошибку. Видимо какая то модель кривая и в forecasts выдает шестизначное значение при вызове def _grad_conf_int(forecasts, p_value) -> tuple[float, float]:
GRAD    4.109873e-01
GRAD   -4.212093e-01
GRAD    3.800560e-01
GRAD    1.965596e-01
GRAD    3.343858e-01
GRAD    3.358879e-01
GRAD    2.790073e-01
GRAD    3.194761e+06
GRAD    1.194737e-01
GRAD    4.888292e-01
GRAD    7.380760e-01
Name: AAL-RM, dtype: float64

Как бы ее найти и грохнуть...

**Comment by WLM1ke** [comment]
Можно в MongoDB глянуть модель с аномально низким llh - скорее всего она.

**Comment by WLM1ke** [comment]
Еще вариант подождать до завтра - возможно погибнет.
Если не погибнет, то глянуть в монге, сколько wins у самых последних моделей. После этого удалить модели с wins меньше этого числа.

**Comment by swpman** [comment]
Спасибо, так и поступлю ;)
