### ISSUE TITLE
отсутствуют (не загружены) данные по MAIL за 14.12.21 - оптимизатор ругается

### ISSUE THREAD

**Issue by swpman** [WLM1ke/poptimizer#90]
$ python -m poptimizer optimize 2021.12.14
{'P_VALUE': 0.05, 'FORECAST_DAYS': 21, 'HISTORY_DAYS_MIN': 63, 'TARGET_POPULATION': 100, 'START_EVOLVE_HOUR': 1, 'STOP_EVOLVE_HOUR': 1, 'COSTS': 0.025, 'MARKET_IMPACT_FACTOR': 1, 'OPTIMIZER': 'resample'}
DateCheckRequired(timestamp=datetime.datetime(2021, 12, 15, 7, 40, 13, 992642))
Forecasts: 1it [00:20, 20.82s/it]
Traceback (most recent call last):
  File "/PATH_TO/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'MAIL'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/PATH_TO/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/PATH_TO/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/PATH_TO/poptimizer/poptimizer/__main__.py", line 46, in <module>
    app(prog_name="poptimizer")
  File "/PATH_TO/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/PATH_TO/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/PATH_TO/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/PATH_TO/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/PATH_TO/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/PATH_TO/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/PATH_TO/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/PATH_TO/poptimizer/poptimizer/__main__.py", line 32, in optimize
    opt = opt_type(port)
  File "/PATH_TO/poptimizer/poptimizer/portfolio/optimizer_resample.py", line 41, in __init__
    self._metrics = metrics.MetricsResample(portfolio)
  File "/PATH_TO/poptimizer/poptimizer/portfolio/metrics.py", line 154, in __init__
    for forecast in evolve.get_forecasts(tickers, date):
  File "/PATH_TO/poptimizer/poptimizer/evolve/forecaster.py", line 140, in get_forecasts
    return cache()
  File "/PATH_TO/poptimizer/poptimizer/evolve/forecaster.py", line 96, in __call__
    return self._create_cache()
  File "/PATH_TO/poptimizer/poptimizer/evolve/forecaster.py", line 114, in _create_cache
    forecasts = Forecasts(self._tickers, self._date)
  File "/PATH_TO/poptimizer/poptimizer/evolve/forecaster.py", line 31, in __init__
    self._forecasts = forecasts or _prepare_forecasts(tickers, date)
  File "/PATH_TO/poptimizer/poptimizer/evolve/forecaster.py", line 64, in _prepare_forecasts
    forecast = organism.forecast(tickers, date)
  File "/PATH_TO/poptimizer/poptimizer/evolve/population.py", line 156, in forecast
    forecast = model.forecast()
  File "/PATH_TO/poptimizer/poptimizer/dl/model.py", line 288, in forecast
    loader = data_loader.DescribedDataLoader(
  File "/PATH_TO/poptimizer/poptimizer/dl/data_loader.py", line 67, in __init__
    data_sets = [OneTickerDataset(ticker, params) for ticker in tickers]
  File "/PATH_TO/poptimizer/poptimizer/dl/data_loader.py", line 67, in <listcomp>
    data_sets = [OneTickerDataset(ticker, params) for ticker in tickers]
  File "/PATH_TO/poptimizer/poptimizer/dl/data_loader.py", line 19, in __init__
    self.features = [
  File "/PATH_TO/poptimizer/poptimizer/dl/data_loader.py", line 20, in <listcomp>
    getattr(features, feat_name)(ticker, params) for feat_name in params.get_all_feat()
  File "/PATH_TO/poptimizer/poptimizer/dl/features/ticker_type.py", line 23, in __init__
    ticker_type = listing.ticker_types()[ticker]
  File "/PATH_TO/lib/python3.9/site-packages/pandas/core/series.py", line 942, in __getitem__
    return self._get_value(key)
  File "/PATH_TO/lib/python3.9/site-packages/pandas/core/series.py", line 1051, in _get_value
    loc = self.index.get_loc(label)
  File "/PATH_TO/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'MAIL'

**Comment by WLM1ke** [comment]
Знаю - нужно исключить MAIL и UWGN. В следующей версии поправлю.
