### ISSUE TITLE
ДАННЫЕ ПО ДИВИДЕНДАМ ТРЕБУЮТ ОБНОВЛЕНИЯ

### ISSUE THREAD

**Issue by ErQrYfkrju** [WLM1ke/poptimizer#94]
ДАННЫЕ ПО ДИВИДЕНДАМ ТРЕБУЮТ ОБНОВЛЕНИЯ

JNJ-RM, VTRS-RM

Обучение шло по тикерам из base.yaml
Сутки крутилось на видеокарточке... После попытался с оптимизировать портфель на вчерашнюю даты выдал что нет дивидентов по этим двум тикерам.
Создал отдельный портфель в котором исключил тикеры с -RM на конце. и попробовал оптимизировать только этот портфель в итоге он выдал 
```
poptimizer.evolve.population.ForecastError: Отсутствуют прогнозы - необходимо обучить модели. SymDiff: {'ABBV-RM', 'CMCSA-RM', 'KHC-RM', 'MRN
A-RM', 'IBM-RM', 'AMZN-RM', 'NEE-RM', 'BIIB-RM', 'MSFT-RM', 'AAPL-RM', 'NFLX-RM', 'BIDU-RM', 'PYPL-RM', 'WMT-RM', 'CRM-RM', 'HPQ-RM', 'PFE-RM
', 'NEM-RM', 'TGT-RM', 'JNJ-RM', 'AVGO-RM', 'DIS-RM', 'GM-RM', 'BABA-RM', 'SBUX-RM', 'CVX-RM', 'EA-RM', 'AMD-RM', 'PG-RM', 'ATVI-RM', 'MCD-RM
', 'TWTR-RM', 'BMY-RM', 'F-RM', 'TSLA-RM', 'ADBE-RM', 'MA-RM', 'VTRS-RM', 'FDX-RM', 'ABT-RM', 'NKE-RM', 'QCOM-RM', 'GPS-RM', 'INTC-RM', 'FB-R
M', 'NVDA-RM', 'UBER-RM', 'GOOG-RM', 'EBAY-RM', 'T-RM', 'V-RM', 'CAT-RM', 'KO-RM', 'AAL-RM', 'GE-RM', 'CSCO-RM', 'XOM-RM'}
``` 
как раз удалённых тикеров по которым как раз модели и обучались...

**Comment by WLM1ke** [comment]
> JNJ-RM, VTRS-RM

Это оповещение о будущих дивидендах, поэтому оно не критично для обучения и текущих прогнозов - служит предупреждением, что нужно не забыть их обновиь. Я дивиденды обновляю примерно раз в неделю по пятницам. В принципе можно самому обновить в базе source.

> Создал отдельный портфель в котором исключил тикеры с -RM на конце.

Обучение идет под конкретный набор тикеров - если набор изменился, то модели нужно переобучать под него. Новые модели будут создаваться для нового набора тикеров, а старые модели будут переобучены на следующий день, поэтому я стараюсь менять перечень тикеров вечером в пятницу, чтобы в выходные все старые модели переучились и были готовы к понедельнику.

**Comment by ErQrYfkrju** [comment]
но там же в коде вроде набор тикеров считывается из всех портфелей и подается на обучение всем скопом(у меня был base.yaml из репозитория плюс он же без -RM),
почему же когда я оптимизирую на выборке с меньшим набором тикеров он говорит что там чего то не хватает что там точно было. вот этого понять не могу

**Comment by WLM1ke** [comment]
Чего-то я перестал понимать, что вы делали. Я так понял, что вы учили на наборе тикеров из base.yaml, а потом удалили все тикеры, оканчивающиеся на -RM. Если это так, то перечень поменялся и нужно переобучить на новый сокращенный список. 

Или вы что-то другое сделали?

**Comment by ErQrYfkrju** [comment]
Тоесть, по факту, сокращенного списка не было они укладывались в тот перечень что был на момент обучения...

**Comment by WLM1ke** [comment]
> 1. взял два файла base.yaml c 0 величинами везде и такой же только выставил 10000 RUB (master.yaml)
> 2. запустил обучение на сутки
> 3. запустил оптимизацию, она выдала ошибки как в соседнем issue плюс предупреждение о дивах

Не очень понял, что за ошибка возникла - можно распечатку. Предупреждение не должно ничему мешать. 

> 4. убрал из master.yaml *-RM
> 5. запустил оптимизацию только для мастера, выругалась система что нет обученных моделей на тикерах *-RM

Вы только master.yaml убрали, а в base.yaml оставили? Тогда я не очень понимаю, что там у вас происходит. 

> И правильно я понимаю что, чтобы была оптимизация, нужно чтобы какой то заранее готовый портфель уже был, а не так что у меня 10 000 и 0 по всем позициям которые я хотел бы учитывать в портфеле

Для оптимизации нужна хотя бы одна не нулевая позиция по бумагам. Для обучения это не принципиально.

**Comment by WLM1ke** [comment]
> Тоесть, по факту, сокращенного списка не было они укладывались в тот перечень что был на момент обучения...

Важно чтобы объединенный перечень бумаг на момент оптимизации по всем файлам не укладывался (был под множеством), а точно совпадал с тем, что был на момент обучения.

**Comment by ErQrYfkrju** [comment]
3. пункт
```
]0;user@0f908ea2e285: /opt/appuser@0f908ea2e285:/opt/app$ [Kpython3.9 -m poptimizer optimize 2022-01-12 1
/home/user/config/config.yaml
{'P_VALUE': 0.05, 'FORECAST_DAYS': 21, 'HISTORY_DAYS_MIN': 60, 'START_EVOLVE_HOUR': 0, 'STOP_EVOLVE_HOUR': 16, 'COSTS': 0.06, 'TRADING_INTERVAL': 1, 'OPTIMIZER': 'resample'}
DateCheckRequired(timestamp=datetime.datetime(2022, 1, 12, 17, 40, 7, 506482))

Forecasts: 0it [00:00, ?it/s]
....
Forecasts: 77it [10:08,  7.90s/it]
ПОРТФЕЛЬ [base, master] - 2022-01-11

Количество бумаг - 206
Открытых позиций - 0

           LOT_SIZE   SHARES    PRICE    VALUE  WEIGHT      TURNOVER
CASH              1  10000.0      1.0  10000.0     1.0  1.020039e+07
PORTFOLIO         1      1.0  10000.0  10000.0     1.0  1.020039e+07
/opt/app/poptimizer/portfolio/metrics.py:101: RuntimeWarning: invalid value encountered in true_divide
  beta = beta / (weight.reshape(1, -1) @ beta)
/opt/app/poptimizer/portfolio/metrics.py:332: RuntimeWarning: invalid value encountered in double_scalars
  dd = self.std[PORTFOLIO] ** 2 / self.mean[PORTFOLIO]
/opt/app/poptimizer/portfolio/metrics.py:332: RuntimeWarning: invalid value encountered in double_scalars
  dd = self.std[PORTFOLIO] ** 2 / self.mean[PORTFOLIO]
/opt/app/poptimizer/portfolio/metrics.py:332: RuntimeWarning: invalid value encountered in double_scalars
  dd = self.std[PORTFOLIO] ** 2 / self.mean[PORTFOLIO]

КЛЮЧЕВЫЕ МЕТРИКИ ПОРТФЕЛЯ

History days - (61 <-> 114 <-> 174)
Correlation - (9.57% <-> 10.55% <-> 13.59%)
Shrinkage - (36.86% <-> 41.71% <-> 48.14%)
Risk aversion - (1.00 <-> 1.00 <-> 1.00)
Error tolerance - (0.00 <-> 0.00 <-> 0.00)

               MEAN       STD  BETA  R_ADJ  GRAD
AAL-RM     0.249195  0.447004   NaN    NaN   NaN
AAPL-RM    0.263979  0.463513   NaN    NaN   NaN
ABBV-RM    0.246622  0.438078   NaN    NaN   NaN
ABRD       0.234385  0.391279   NaN    NaN   NaN
ABT-RM     0.257390  0.454613   NaN    NaN   NaN
ADBE-RM    0.263902  0.469526   NaN    NaN   NaN
AFKS       0.248660  0.445760   NaN    NaN   NaN
AFLT       0.249885  0.442962   NaN    NaN   NaN
AGRO       0.245178  0.420940   NaN    NaN   NaN
AKRN       0.248925  0.453220   NaN    NaN   NaN
ALRS       0.240706  0.408825   NaN    NaN   NaN
AMD-RM     0.285018  0.526912   NaN    NaN   NaN
AMEZ       0.257390  0.457733   NaN    NaN   NaN
AMZN-RM    0.257390  0.473274   NaN    NaN   NaN
APTK       0.241891  0.426900   NaN    NaN   NaN
AQUA       0.284005  0.515023   NaN    NaN   NaN
ATVI-RM    0.248098  0.441409   NaN    NaN   NaN
AVGO-RM    0.248918  0.442531   NaN    NaN   NaN
BA-RM      0.248098  0.441449   NaN    NaN   NaN
BABA-RM    0.256597  0.472672   NaN    NaN   NaN
BANE       0.234670  0.399879   NaN    NaN   NaN
BANEP      0.237412  0.405084   NaN    NaN   NaN
BELU       0.248141  0.443121   NaN    NaN   NaN
BIDU-RM    0.262838  0.475671   NaN    NaN   NaN
BIIB-RM    0.264085  0.473768   NaN    NaN   NaN
BMY-RM     0.241078  0.411450   NaN    NaN   NaN
BRZL       0.234457  0.409069   NaN    NaN   NaN
BSPB       0.248960  0.434487   NaN    NaN   NaN
CAT-RM     0.248098  0.443856   NaN    NaN   NaN
CBOM       0.214698  0.351389   NaN    NaN   NaN
CHMF       0.242522  0.404328   NaN    NaN   NaN
CHMK       0.256508  0.440585   NaN    NaN   NaN
CMCSA-RM   0.248099  0.437513   NaN    NaN   NaN
CNTL       0.247159  0.429958   NaN    NaN   NaN
CNTLP      0.247902  0.440899   NaN    NaN   NaN
CRM-RM     0.248098  0.419396   NaN    NaN   NaN
CSCO-RM    0.240724  0.422755   NaN    NaN   NaN
CVX-RM     0.245184  0.432416   NaN    NaN   NaN
DIOD       0.242939  0.407516   NaN    NaN   NaN
DIS-RM     0.231773  0.402194   NaN    NaN   NaN
DSKY       0.235065  0.386016   NaN    NaN   NaN
EA-RM      0.232804  0.408680   NaN    NaN   NaN
EBAY-RM    0.240204  0.406318   NaN    NaN   NaN
EELT       0.231853  0.397143   NaN    NaN   NaN
ENPG       0.258598  0.464809   NaN    NaN   NaN
ENRU       0.242805  0.414918   NaN    NaN   NaN
ETLN       0.230461  0.389553   NaN    NaN   NaN
F-RM       0.299522  0.564674   NaN    NaN   NaN
FB-RM      0.247483  0.441309   NaN    NaN   NaN
FDX-RM     0.259079  0.488585   NaN    NaN   NaN
FEES       0.240224  0.407064   NaN    NaN   NaN
FESH       0.296684  0.511153   NaN    NaN   NaN
FIVE       0.245062  0.422960   NaN    NaN   NaN
FLOT       0.217006  0.377954   NaN    NaN   NaN
FXCN       0.219265  0.328271   NaN    NaN   NaN
FXGD       0.220429  0.311004   NaN    NaN   NaN
FXIT       0.220535  0.312484   NaN    NaN   NaN
FXMM       0.186502  0.235467   NaN    NaN   NaN
FXRB       0.193703  0.258526   NaN    NaN   NaN
FXRU       0.202323  0.266380   NaN    NaN   NaN
GAZP       0.243373  0.417109   NaN    NaN   NaN
GCHE       0.248403  0.429156   NaN    NaN   NaN
GE-RM      0.233165  0.395564   NaN    NaN   NaN
GEMA       0.252505  0.448650   NaN    NaN   NaN
GLTR       0.248068  0.416248   NaN    NaN   NaN
GM-RM      0.263902  0.488155   NaN    NaN   NaN
GMKN       0.240706  0.398874   NaN    NaN   NaN
GOOG-RM    0.245195  0.415398   NaN    NaN   NaN
GPS-RM     0.252012  0.464078   NaN    NaN   NaN
GTRK       0.243925  0.440230   NaN    NaN   NaN
HHRU       0.262058  0.463182   NaN    NaN   NaN
HIMCP      0.262580  0.446616   NaN    NaN   NaN
HPQ-RM     0.265866  0.476397   NaN    NaN   NaN
HYDR       0.240073  0.403030   NaN    NaN   NaN
IBM-RM     0.240706  0.414556   NaN    NaN   NaN
INGR       0.250169  0.439600   NaN    NaN   NaN
INTC-RM    0.244462  0.420255   NaN    NaN   NaN
IRAO       0.240784  0.405541   NaN    NaN   NaN
IRKT       0.248979  0.432469   NaN    NaN   NaN
ISKJ       0.291783  0.575383   NaN    NaN   NaN
JNJ-RM     0.240706  0.426049   NaN    NaN   NaN
KAZT       0.242919  0.417199   NaN    NaN   NaN
KHC-RM     0.232876  0.405259   NaN    NaN   NaN
KLSB       0.263901  0.478945   NaN    NaN   NaN
KMAZ       0.246325  0.436114   NaN    NaN   NaN
KO-RM      0.235625  0.405033   NaN    NaN   NaN
KRKNP      0.232650  0.379075   NaN    NaN   NaN
KRSB       0.240073  0.403263   NaN    NaN   NaN
KZOS       0.239988  0.398151   NaN    NaN   NaN
LIFE       0.250679  0.459428   NaN    NaN   NaN
LKOH       0.243241  0.403845   NaN    NaN   NaN
LNTA       0.243211  0.414742   NaN    NaN   NaN
LNZL       0.245454  0.428123   NaN    NaN   NaN
LNZLP      0.244311  0.405301   NaN    NaN   NaN
LSNG       0.260392  0.461439   NaN    NaN   NaN
LSNGP      0.237278  0.400283   NaN    NaN   NaN
LSRG       0.236030  0.397707   NaN    NaN   NaN
MA-RM      0.240706  0.419178   NaN    NaN   NaN
MAGN       0.252005  0.443950   NaN    NaN   NaN
MCD-RM     0.243273  0.414004   NaN    NaN   NaN
MDMG       0.245513  0.420422   NaN    NaN   NaN
MGNT       0.253336  0.437598   NaN    NaN   NaN
MGTSP      0.235868  0.390659   NaN    NaN   NaN
MOEX       0.232389  0.396107   NaN    NaN   NaN
MRKC       0.248098  0.421090   NaN    NaN   NaN
MRKP       0.240706  0.410838   NaN    NaN   NaN
MRKS       0.278182  0.496380   NaN    NaN   NaN
MRKU       0.255578  0.453237   NaN    NaN   NaN
MRKV       0.250524  0.444005   NaN    NaN   NaN
MRKY       0.252099  0.449872   NaN    NaN   NaN
MRKZ       0.255637  0.446455   NaN    NaN   NaN
MRNA-RM    0.257390  0.466708   NaN    NaN   NaN
MRSB       0.266579  0.473272   NaN    NaN   NaN
MSFT-RM    0.253160  0.447692   NaN    NaN   NaN
MSNG       0.239439  0.402496   NaN    NaN   NaN
MSRS       0.237325  0.410180   NaN    NaN   NaN
MSTT       0.237737  0.406519   NaN    NaN   NaN
MTLR       0.276403  0.501644   NaN    NaN   NaN
MTLRP      0.292577  0.540220   NaN    NaN   NaN
MTSS       0.225965  0.377502   NaN    NaN   NaN
MU-RM      0.264999  0.471472   NaN    NaN   NaN
MVID       0.231035  0.381721   NaN    NaN   NaN
NEE-RM     0.257937  0.449944   NaN    NaN   NaN
NEM-RM     0.247204  0.450786   NaN    NaN   NaN
NFAZ       0.290491  0.530553   NaN    NaN   NaN
NFLX-RM    0.259789  0.455960   NaN    NaN   NaN
NKE-RM     0.264296  0.473934   NaN    NaN   NaN
NKHP       0.232082  0.399265   NaN    NaN   NaN
NKNC       0.240944  0.408841   NaN    NaN   NaN
NKNCP      0.244901  0.416582   NaN    NaN   NaN
NLMK       0.246655  0.423362   NaN    NaN   NaN
NMTP       0.240706  0.408129   NaN    NaN   NaN
NSVZ       0.262250  0.470009   NaN    NaN   NaN
NVDA-RM    0.288465  0.542187   NaN    NaN   NaN
NVTK       0.237422  0.404222   NaN    NaN   NaN
OGKB       0.254471  0.438641   NaN    NaN   NaN
ORUP       0.248098  0.432107   NaN    NaN   NaN
OZON       0.241126  0.414987   NaN    NaN   NaN
PFE-RM     0.270385  0.501616   NaN    NaN   NaN
PG-RM      0.239502  0.411664   NaN    NaN   NaN
PHOR       0.240706  0.397598   NaN    NaN   NaN
PIKK       0.240073  0.402661   NaN    NaN   NaN
PLZL       0.247467  0.426425   NaN    NaN   NaN
PMSBP      0.229417  0.370286   NaN    NaN   NaN
POGR       0.259835  0.445311   NaN    NaN   NaN
POLY       0.252508  0.439732   NaN    NaN   NaN
PYPL-RM    0.258729  0.463410   NaN    NaN   NaN
QCOM-RM    0.269627  0.485357   NaN    NaN   NaN
QIWI       0.269700  0.477305   NaN    NaN   NaN
RASP       0.296056  0.511153   NaN    NaN   NaN
RBCM       0.248979  0.442599   NaN    NaN   NaN
RGSS       0.244409  0.432829   NaN    NaN   NaN
RNFT       0.250651  0.445935   NaN    NaN   NaN
ROLO       0.260097  0.471472   NaN    NaN   NaN
ROSN       0.244972  0.410508   NaN    NaN   NaN
RSTI       0.260299  0.457750   NaN    NaN   NaN
RSTIP      0.244237  0.415595   NaN    NaN   NaN
RTKM       0.216705  0.378146   NaN    NaN   NaN
RTKMP      0.225822  0.359878   NaN    NaN   NaN
RUAL       0.269840  0.488874   NaN    NaN   NaN
RUGR       0.268288  0.490033   NaN    NaN   NaN
RZSB       0.260096  0.456316   NaN    NaN   NaN
SBER       0.248975  0.428777   NaN    NaN   NaN
SBERP      0.241556  0.404939   NaN    NaN   NaN
SBRB       0.198499  0.265381   NaN    NaN   NaN
SBUX-RM    0.235412  0.405882   NaN    NaN   NaN
SELG       0.257390  0.441002   NaN    NaN   NaN
SFIN       0.245258  0.418624   NaN    NaN   NaN
SIBN       0.245273  0.412283   NaN    NaN   NaN
SMLT       0.329651  0.571191   NaN    NaN   NaN
SNGS       0.244839  0.414418   NaN    NaN   NaN
SNGSP      0.230543  0.376423   NaN    NaN   NaN
STSBP      0.262978  0.452535   NaN    NaN   NaN
SVAV       0.242108  0.424192   NaN    NaN   NaN
T-RM       0.236289  0.407322   NaN    NaN   NaN
TATN       0.246855  0.429635   NaN    NaN   NaN
TATNP      0.246912  0.415395   NaN    NaN   NaN
TCSG       0.269420  0.454613   NaN    NaN   NaN
TGKA       0.246118  0.423592   NaN    NaN   NaN
TGKB       0.262343  0.469526   NaN    NaN   NaN
TGKD       0.274821  0.481657   NaN    NaN   NaN
TGKN       0.239918  0.413672   NaN    NaN   NaN
TGT-RM     0.248096  0.432961   NaN    NaN   NaN
TRMK       0.244975  0.432349   NaN    NaN   NaN
TRNFP      0.238674  0.406518   NaN    NaN   NaN
TRUR       0.198286  0.272128   NaN    NaN   NaN
TSLA-RM    0.290475  0.544280   NaN    NaN   NaN
TTLK       0.247052  0.421758   NaN    NaN   NaN
TWTR-RM    0.264157  0.480206   NaN    NaN   NaN
UBER-RM    0.265645  0.500082   NaN    NaN   NaN
UNAC       0.248351  0.443062   NaN    NaN   NaN
UNKL       0.246028  0.433831   NaN    NaN   NaN
UPRO       0.226310  0.377278   NaN    NaN   NaN
USBN       0.254545  0.454613   NaN    NaN   NaN
V-RM       0.238533  0.406833   NaN    NaN   NaN
VKCO       0.238697  0.407740   NaN    NaN   NaN
VSMO       0.248098  0.439982   NaN    NaN   NaN
VTBB       0.192952  0.261830   NaN    NaN   NaN
VTBM       0.196996  0.258526   NaN    NaN   NaN
VTBR       0.240073  0.414919   NaN    NaN   NaN
VTRS-RM    0.246170  0.429330   NaN    NaN   NaN
WMT-RM     0.240706  0.410217   NaN    NaN   NaN
XOM-RM     0.256020  0.441768   NaN    NaN   NaN
YAKG       0.263856  0.476139   NaN    NaN   NaN
YNDX       0.248098  0.421195   NaN    NaN   NaN
ZILL       0.250174  0.451849   NaN    NaN   NaN
CASH       0.000000  0.000000   0.0    0.0   0.0
PORTFOLIO  0.000000  0.000000   1.0    0.0   0.0

Консервативная доходность:  0.00%
Консервативный риск:        0.00%
Консервативная метрика:     0.00%
Оценка просадки:            nan%
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python3.9/logging/handlers.py", line 191, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 365, in getMessage
    msg = str(self.msg)
  File "/opt/app/poptimizer/portfolio/optimizer_resample.py", line 45, in __str__
    df = self._for_trade()
  File "/opt/app/poptimizer/portfolio/optimizer_resample.py", line 68, in _for_trade
    conf_int = self._prepare_bounds()
  File "/opt/app/poptimizer/portfolio/optimizer_resample.py", line 114, in _prepare_bounds
    conf_int = conf_int.apply(
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/frame.py", line 8740, in apply
    return op.apply()
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/apply.py", line 688, in apply
    return self.apply_standard()
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/apply.py", line 812, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/apply.py", line 828, in apply_series_generator
    results[i] = self.f(v)
  File "/opt/app/poptimizer/portfolio/optimizer_resample.py", line 115, in <lambda>
    lambda grad: _grad_conf_int(grad, p_value),
  File "/opt/app/poptimizer/portfolio/optimizer_resample.py", line 184, in _grad_conf_int
    interval = stats.bootstrap(
  File "/usr/local/lib/python3.9/dist-packages/scipy/stats/_bootstrap.py", line 454, in bootstrap
    ci_l = percentile_fun(theta_hat_b, interval[0]*100)
  File "/usr/local/lib/python3.9/dist-packages/scipy/stats/_bootstrap.py", line 78, in _percentile_along_axis
    percentiles[indices] = np.percentile(theta_hat_b_i, alpha_i)
  File "<__array_function__ internals>", line 180, in percentile
  File "/usr/local/lib/python3.9/dist-packages/numpy/lib/function_base.py", line 4133, in percentile
    raise ValueError("Percentiles must be in the range [0, 100]")
ValueError: Percentiles must be in the range [0, 100]
Call stack:
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/app/poptimizer/__main__.py", line 46, in <module>
    app(prog_name="poptimizer")
  File "/usr/local/lib/python3.9/dist-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/app/poptimizer/__main__.py", line 35, in optimize
    LOGGER.info(opt)
Message: <poptimizer.portfolio.optimizer_resample.Optimizer object at 0x7fb67e4e5e80>
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 365, in getMessage
    msg = str(self.msg)
  File "/opt/app/poptimizer/portfolio/optimizer_resample.py", line 45, in __str__
    df = self._for_trade()
  File "/opt/app/poptimizer/portfolio/optimizer_resample.py", line 68, in _for_trade
    conf_int = self._prepare_bounds()
  File "/opt/app/poptimizer/portfolio/optimizer_resample.py", line 114, in _prepare_bounds
    conf_int = conf_int.apply(
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/frame.py", line 8740, in apply
    return op.apply()
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/apply.py", line 688, in apply
    return self.apply_standard()
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/apply.py", line 812, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/apply.py", line 828, in apply_series_generator
    results[i] = self.f(v)
  File "/opt/app/poptimizer/portfolio/optimizer_resample.py", line 115, in <lambda>
    lambda grad: _grad_conf_int(grad, p_value),
  File "/opt/app/poptimizer/portfolio/optimizer_resample.py", line 184, in _grad_conf_int
    interval = stats.bootstrap(
  File "/usr/local/lib/python3.9/dist-packages/scipy/stats/_bootstrap.py", line 454, in bootstrap
    ci_l = percentile_fun(theta_hat_b, interval[0]*100)
  File "/usr/local/lib/python3.9/dist-packages/scipy/stats/_bootstrap.py", line 78, in _percentile_along_axis
    percentiles[indices] = np.percentile(theta_hat_b_i, alpha_i)
  File "<__array_function__ internals>", line 180, in percentile
  File "/usr/local/lib/python3.9/dist-packages/numpy/lib/function_base.py", line 4133, in percentile
    raise ValueError("Percentiles must be in the range [0, 100]")
ValueError: Percentiles must be in the range [0, 100]
Call stack:
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/app/poptimizer/__main__.py", line 46, in <module>
    app(prog_name="poptimizer")
  File "/usr/local/lib/python3.9/dist-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/app/poptimizer/__main__.py", line 35, in optimize
    LOGGER.info(opt)
Message: <poptimizer.portfolio.optimizer_resample.Optimizer object at 0x7fb67e4e5e80>
Arguments: ()

ДАННЫЕ ПО ДИВИДЕНДАМ ТРЕБУЮТ ОБНОВЛЕНИЯ

VTRS-RM, JNJ-RM
```

**Comment by WLM1ke** [comment]
Ошибка, трейс которой вы привели, видимо связана с нулевыми позициями по бумагам - нужна хотя бы одна не нулевая позиция.

**Comment by ErQrYfkrju** [comment]
> 

в обоих файлах или только в одном?

**Comment by WLM1ke** [comment]
> Судя по истории разработки RomaKoks добавил возможность оптимизации только выбранного портфеля. я воспользовался этим функционалом он меня "отругал". И не понятно что значит объединенный перечень бумаг на момент оптимизации. если у меня было два портфеля на момент evolve он их посчитал, а оптимизировать я хочу только один из них, получится что это уже подмножество объединенного.... правильно?

Да, так не будет работать. Нужно учить и оптимизировать на одинаковом наборе тикеров. Завтра модели будут переучиваться на новый набор.

**Comment by ErQrYfkrju** [comment]
> > в обоих файлах или только в одном?
> 
> Не уверен, что я вас правильно понимаю. Все файлы в папке portfolio объединяются - формируется единый портфель, как сумма портфелей в отдельных файлах. Вот в этом едином портфеле хотя бы по одной бумаге должна быть не нулевая позиция, иначе возникнет деление на ноль и получится примерно, что у вас вышло. Или другими словами достаточно, чтобы хотя бы в одном файле хотя бы по одной бумаге была не нулевая позиция.

Понятно.

**Comment by ErQrYfkrju** [comment]
В целом уяснил буду дальше изучать ваш софт. 
Спасибо!

**Comment by ErQrYfkrju** [comment]
В целом уяснил буду дальше изучать ваш софт. 
Спасибо!
